# Generated by Django 6.0.3 on 2026-04-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseZone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StdID', models.AutoField(primary_key=True, serialize=False)),
                ('StdName', models.CharField(max_length=100)),
                ('StdAge', models.IntegerField()),
                ('StdEmail', models.EmailField(max_length=254)),
                ('StdPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
